//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineDirect.v42
{

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://winedirect.com/4/2/dtc/", ConfigurationName = "dtcSoap")]
	public interface dtcSoap
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/2/dtc/GetDeliveryOptions", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetDeliveryOptionsResponse> GetDeliveryOptionsAsync(GetDeliveryOptionsRequest GetDeliveryOptionsRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/2/dtc/SubmitOrders", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<SubmitOrdersResponse> SubmitOrdersAsync(SubmitOrdersRequest SubmitOrdersRequest);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class GetDeliveryOptionsRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private Address addressField;

		private System.Nullable<int> searchRadiusMilesField;

		private System.Nullable<int> maxResultsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Address Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
		public System.Nullable<int> SearchRadiusMiles {
			get {
				return this.searchRadiusMilesField;
			}
			set {
				this.searchRadiusMilesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
		public System.Nullable<int> MaxResults {
			get {
				return this.maxResultsField;
			}
			set {
				this.maxResultsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class AuthenticationInfo
	{

		private string userNameField;

		private string passwordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string UserName {
			get {
				return this.userNameField;
			}
			set {
				this.userNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Password {
			get {
				return this.passwordField;
			}
			set {
				this.passwordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class DtcOrderLine
	{

		private int lineNumberField;

		private int quantityField;

		private string sKUField;

		private double unitPriceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int LineNumber {
			get {
				return this.lineNumberField;
			}
			set {
				this.lineNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public double UnitPrice {
			get {
				return this.unitPriceField;
			}
			set {
				this.unitPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class AddressInfo
	{

		private string companyNameField;

		private string line1Field;

		private string line2Field;

		private string line3Field;

		private string cityField;

		private string stateOrProvinceField;

		private string postalCodeField;

		private string countryCodeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string CompanyName {
			get {
				return this.companyNameField;
			}
			set {
				this.companyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Line1 {
			get {
				return this.line1Field;
			}
			set {
				this.line1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Line2 {
			get {
				return this.line2Field;
			}
			set {
				this.line2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string Line3 {
			get {
				return this.line3Field;
			}
			set {
				this.line3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string PostalCode {
			get {
				return this.postalCodeField;
			}
			set {
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string CountryCode {
			get {
				return this.countryCodeField;
			}
			set {
				this.countryCodeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class ConsumerInfo
	{

		private string consumerIdField;

		private string firstNameField;

		private string middleNameField;

		private string lastNameField;

		private string emailAddressField;

		private string telephoneNumberField;

		private AddressInfo addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string ConsumerId {
			get {
				return this.consumerIdField;
			}
			set {
				this.consumerIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string FirstName {
			get {
				return this.firstNameField;
			}
			set {
				this.firstNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string MiddleName {
			get {
				return this.middleNameField;
			}
			set {
				this.middleNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string LastName {
			get {
				return this.lastNameField;
			}
			set {
				this.lastNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string EmailAddress {
			get {
				return this.emailAddressField;
			}
			set {
				this.emailAddressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string TelephoneNumber {
			get {
				return this.telephoneNumberField;
			}
			set {
				this.telephoneNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public AddressInfo Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class DtcOrder
	{

		private string orderIdField;

		private string batchIdField;

		private DtcOrderTypeEnum orderTypeField;

		private bool onSitePurchaseField;

		private string warehouseCodeField;

		private string subinventoryCodeField;

		private string notificationCodeField;

		private string packingSlipCodeField;

		private string giftMessageField;

		private string reference1Field;

		private string reference2Field;

		private string reference3Field;

		private ConsumerInfo soldToField;

		private ConsumerInfo shipToField;

		private string deliveryAddressTypeField;

		private string deliveryAddressIDField;

		private ConsumerInfo deliverToField;

		private string deliveryAddressAttribute1Field;

		private string deliveryAddressAttribute2Field;

		private string deliveryAddressAttribute3Field;

		private string requestedPriorityField;

		private string requestedShipDateField;

		private string shippingInstructionsField;

		private double shippingChargesField;

		private double handlingChargesField;

		private double salesTaxField;

		private double insuranceField;

		private double totalSaleField;

		private DtcOrderLine[] orderLinesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public DtcOrderTypeEnum OrderType {
			get {
				return this.orderTypeField;
			}
			set {
				this.orderTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public bool OnSitePurchase {
			get {
				return this.onSitePurchaseField;
			}
			set {
				this.onSitePurchaseField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string SubinventoryCode {
			get {
				return this.subinventoryCodeField;
			}
			set {
				this.subinventoryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string NotificationCode {
			get {
				return this.notificationCodeField;
			}
			set {
				this.notificationCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string PackingSlipCode {
			get {
				return this.packingSlipCodeField;
			}
			set {
				this.packingSlipCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public string GiftMessage {
			get {
				return this.giftMessageField;
			}
			set {
				this.giftMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public string Reference1 {
			get {
				return this.reference1Field;
			}
			set {
				this.reference1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public string Reference2 {
			get {
				return this.reference2Field;
			}
			set {
				this.reference2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 11)]
		public string Reference3 {
			get {
				return this.reference3Field;
			}
			set {
				this.reference3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public ConsumerInfo SoldTo {
			get {
				return this.soldToField;
			}
			set {
				this.soldToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 13)]
		public ConsumerInfo ShipTo {
			get {
				return this.shipToField;
			}
			set {
				this.shipToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 14)]
		public string DeliveryAddressType {
			get {
				return this.deliveryAddressTypeField;
			}
			set {
				this.deliveryAddressTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 15)]
		public string DeliveryAddressID {
			get {
				return this.deliveryAddressIDField;
			}
			set {
				this.deliveryAddressIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 16)]
		public ConsumerInfo DeliverTo {
			get {
				return this.deliverToField;
			}
			set {
				this.deliverToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 17)]
		public string DeliveryAddressAttribute1 {
			get {
				return this.deliveryAddressAttribute1Field;
			}
			set {
				this.deliveryAddressAttribute1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 18)]
		public string DeliveryAddressAttribute2 {
			get {
				return this.deliveryAddressAttribute2Field;
			}
			set {
				this.deliveryAddressAttribute2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 19)]
		public string DeliveryAddressAttribute3 {
			get {
				return this.deliveryAddressAttribute3Field;
			}
			set {
				this.deliveryAddressAttribute3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 20)]
		public string RequestedPriority {
			get {
				return this.requestedPriorityField;
			}
			set {
				this.requestedPriorityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 21)]
		public string RequestedShipDate {
			get {
				return this.requestedShipDateField;
			}
			set {
				this.requestedShipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 22)]
		public string ShippingInstructions {
			get {
				return this.shippingInstructionsField;
			}
			set {
				this.shippingInstructionsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 23)]
		public double ShippingCharges {
			get {
				return this.shippingChargesField;
			}
			set {
				this.shippingChargesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 24)]
		public double HandlingCharges {
			get {
				return this.handlingChargesField;
			}
			set {
				this.handlingChargesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 25)]
		public double SalesTax {
			get {
				return this.salesTaxField;
			}
			set {
				this.salesTaxField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 26)]
		public double Insurance {
			get {
				return this.insuranceField;
			}
			set {
				this.insuranceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 27)]
		public double TotalSale {
			get {
				return this.totalSaleField;
			}
			set {
				this.totalSaleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 28)]
		public DtcOrderLine[] OrderLines {
			get {
				return this.orderLinesField;
			}
			set {
				this.orderLinesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public enum DtcOrderTypeEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Club,

		/// <remarks/>
		Daily,

		/// <remarks/>
		Special,

		/// <remarks/>
		Sample,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class SubmitOrdersRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private DtcOrder[] ordersField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public DtcOrder[] Orders {
			get {
				return this.ordersField;
			}
			set {
				this.ordersField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class HoursOfOperation
	{

		private bool isOpenField;

		private string dayOfWeekField;

		private string openTimeField;

		private string closeTimeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool IsOpen {
			get {
				return this.isOpenField;
			}
			set {
				this.isOpenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string DayOfWeek {
			get {
				return this.dayOfWeekField;
			}
			set {
				this.dayOfWeekField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string OpenTime {
			get {
				return this.openTimeField;
			}
			set {
				this.openTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string CloseTime {
			get {
				return this.closeTimeField;
			}
			set {
				this.closeTimeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class DeliveryOption
	{

		private string locationTypeField;

		private string idField;

		private string companyNameField;

		private string line1Field;

		private string line2Field;

		private string line3Field;

		private string cityField;

		private string stateCodeField;

		private string postalCodeField;

		private string countryCodeField;

		private System.Nullable<double> latitudeField;

		private System.Nullable<double> longitudeField;

		private string phoneNumberField;

		private string faxNumberField;

		private System.Nullable<double> distanceInMilesField;

		private HoursOfOperation[] hoursField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string LocationType {
			get {
				return this.locationTypeField;
			}
			set {
				this.locationTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string ID {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string CompanyName {
			get {
				return this.companyNameField;
			}
			set {
				this.companyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string Line1 {
			get {
				return this.line1Field;
			}
			set {
				this.line1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string Line2 {
			get {
				return this.line2Field;
			}
			set {
				this.line2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string Line3 {
			get {
				return this.line3Field;
			}
			set {
				this.line3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string StateCode {
			get {
				return this.stateCodeField;
			}
			set {
				this.stateCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public string PostalCode {
			get {
				return this.postalCodeField;
			}
			set {
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public string CountryCode {
			get {
				return this.countryCodeField;
			}
			set {
				this.countryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
		public System.Nullable<double> Latitude {
			get {
				return this.latitudeField;
			}
			set {
				this.latitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
		public System.Nullable<double> Longitude {
			get {
				return this.longitudeField;
			}
			set {
				this.longitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public string PhoneNumber {
			get {
				return this.phoneNumberField;
			}
			set {
				this.phoneNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 13)]
		public string FaxNumber {
			get {
				return this.faxNumberField;
			}
			set {
				this.faxNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 14)]
		public System.Nullable<double> DistanceInMiles {
			get {
				return this.distanceInMilesField;
			}
			set {
				this.distanceInMilesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 15)]
		public HoursOfOperation[] Hours {
			get {
				return this.hoursField;
			}
			set {
				this.hoursField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class ErrorReference
	{

		private string nameField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Value {
			get {
				return this.valueField;
			}
			set {
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class ServiceMessage
	{

		private ErrorReference[] referencesField;

		private string codeField;

		private string messageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public ErrorReference[] References {
			get {
				return this.referencesField;
			}
			set {
				this.referencesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Code {
			get {
				return this.codeField;
			}
			set {
				this.codeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Message {
			get {
				return this.messageField;
			}
			set {
				this.messageField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class ServiceOutcome
	{

		private ResultEnum resultField;

		private ServiceMessage[] warningsField;

		private ServiceMessage[] errorsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ResultEnum Result {
			get {
				return this.resultField;
			}
			set {
				this.resultField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public ServiceMessage[] Warnings {
			get {
				return this.warningsField;
			}
			set {
				this.warningsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public ServiceMessage[] Errors {
			get {
				return this.errorsField;
			}
			set {
				this.errorsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public enum ResultEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Success,

		/// <remarks/>
		Failure,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubmitOrdersResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDeliveryOptionsResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class IServiceResponse
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class SubmitOrdersResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class GetDeliveryOptionsResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private DeliveryOption[] optionsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public DeliveryOption[] Options {
			get {
				return this.optionsField;
			}
			set {
				this.optionsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/2/dtc/")]
	public partial class Address
	{

		private string line1Field;

		private string line2Field;

		private string line3Field;

		private string cityField;

		private string stateCodeField;

		private string postalCodeField;

		private string countryCodeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Line1 {
			get {
				return this.line1Field;
			}
			set {
				this.line1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Line2 {
			get {
				return this.line2Field;
			}
			set {
				this.line2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Line3 {
			get {
				return this.line3Field;
			}
			set {
				this.line3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string StateCode {
			get {
				return this.stateCodeField;
			}
			set {
				this.stateCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string PostalCode {
			get {
				return this.postalCodeField;
			}
			set {
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string CountryCode {
			get {
				return this.countryCodeField;
			}
			set {
				this.countryCodeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public interface dtcSoapChannel : dtcSoap, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public partial class dtcSoapClient : System.ServiceModel.ClientBase<dtcSoap>, dtcSoap
	{

		/// <summary>
		/// Implement this partial method to configure the service endpoint.
		/// </summary>
		/// <param name="serviceEndpoint">The endpoint to configure</param>
		/// <param name="clientCredentials">The client credentials</param>
		static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

		public dtcSoapClient(EndpointConfiguration endpointConfiguration) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), dtcSoapClient.GetEndpointAddress(endpointConfiguration)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
				base(binding, remoteAddress) {
		}

		public System.Threading.Tasks.Task<GetDeliveryOptionsResponse> GetDeliveryOptionsAsync(GetDeliveryOptionsRequest GetDeliveryOptionsRequest) {
			return base.Channel.GetDeliveryOptionsAsync(GetDeliveryOptionsRequest);
		}

		public System.Threading.Tasks.Task<SubmitOrdersResponse> SubmitOrdersAsync(SubmitOrdersRequest SubmitOrdersRequest) {
			return base.Channel.SubmitOrdersAsync(SubmitOrdersRequest);
		}

		public virtual System.Threading.Tasks.Task OpenAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
		}

		public virtual System.Threading.Tasks.Task CloseAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
		}

		private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap)) {
				System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
				result.MaxBufferSize = int.MaxValue;
				result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
				result.MaxReceivedMessageSize = int.MaxValue;
				result.AllowCookies = true;
				return result;
			}
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap12)) {
				System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
				System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
				textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
				result.Elements.Add(textBindingElement);
				System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
				httpBindingElement.AllowCookies = true;
				httpBindingElement.MaxBufferSize = int.MaxValue;
				httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
				result.Elements.Add(httpBindingElement);
				return result;
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/2/dtc.asmx");
			}
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap12)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/2/dtc.asmx");
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		public enum EndpointConfiguration
		{

			dtcSoap,

			dtcSoap12,
		}
	}
}