//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineDirect.IWS
{

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://winedirect.com/4/0/internal/", ConfigurationName = "InternalSoap")]
	public interface InternalSoap
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/SearchForAddress", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<SearchForAddressResponse> SearchForAddressAsync(SearchForAddressRequest SearchForAddressRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/RefineAddressSearch", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<RefineAddressSearchResponse> RefineAddressSearchAsync(RefineAddressSearchRequest RefineAddressSearchRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/CreateWineSKU", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CreateWineSKUResponse> CreateWineSKUAsync(CreateWineSKURequest CreateWineSKURequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/CreateNonWineSKU", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CreateNonWineSKUResponse> CreateNonWineSKUAsync(CreateNonWineSKURequest CreateNonWineSKURequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/CreateGiftSetSKU", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CreateGiftSetSKUResponse> CreateGiftSetSKUAsync(CreateGiftSetSKURequest CreateGiftSetSKURequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/CreateBundleSKU", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CreateBundleSKUResponse> CreateBundleSKUAsync(CreateBundleSKURequest CreateBundleSKURequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/DeactivateSKU", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<DeactivateSKUResponse> DeactivateSKUAsync(DeactivateSKURequest DeactivateSKURequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/internal/GetOrderStatus", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductData))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetOrderStatusResponse> GetOrderStatusAsync(GetOrderStatusRequest GetOrderStatusRequest);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class SearchForAddressRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private QASSearchAddress addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public QASSearchAddress Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class AuthenticationInfo
	{

		private string userNameField;

		private string passwordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string UserName {
			get {
				return this.userNameField;
			}
			set {
				this.userNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Password {
			get {
				return this.passwordField;
			}
			set {
				this.passwordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class GetOrderStatusRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private bool searchByBatchIdSpecified1Field;

		private string batchIdField;

		private bool searchByOrderIdsSpecified1Field;

		private string[] orderIdsField;

		private bool searchByStatusSpecified1Field;

		private string statusField;

		private bool searchByReferenceSpecified1Field;

		private string reference1Field;

		private string reference2Field;

		private string reference3Field;

		private string startingOrderIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByBatchIdSpecified", Order = 2)]
		public bool SearchByBatchIdSpecified1 {
			get {
				return this.searchByBatchIdSpecified1Field;
			}
			set {
				this.searchByBatchIdSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByOrderIdsSpecified", Order = 4)]
		public bool SearchByOrderIdsSpecified1 {
			get {
				return this.searchByOrderIdsSpecified1Field;
			}
			set {
				this.searchByOrderIdsSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
		public string[] OrderIds {
			get {
				return this.orderIdsField;
			}
			set {
				this.orderIdsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByStatusSpecified", Order = 6)]
		public bool SearchByStatusSpecified1 {
			get {
				return this.searchByStatusSpecified1Field;
			}
			set {
				this.searchByStatusSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string Status {
			get {
				return this.statusField;
			}
			set {
				this.statusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByReferenceSpecified", Order = 8)]
		public bool SearchByReferenceSpecified1 {
			get {
				return this.searchByReferenceSpecified1Field;
			}
			set {
				this.searchByReferenceSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public string Reference1 {
			get {
				return this.reference1Field;
			}
			set {
				this.reference1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public string Reference2 {
			get {
				return this.reference2Field;
			}
			set {
				this.reference2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 11)]
		public string Reference3 {
			get {
				return this.reference3Field;
			}
			set {
				this.reference3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public string StartingOrderId {
			get {
				return this.startingOrderIdField;
			}
			set {
				this.startingOrderIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DeactivateSKURequest
	{

		private AuthenticationInfo authenticationInfoField;

		private int supplierIDField;

		private string supplierSKUField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int SupplierID {
			get {
				return this.supplierIDField;
			}
			set {
				this.supplierIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SupplierSKU {
			get {
				return this.supplierSKUField;
			}
			set {
				this.supplierSKUField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateBundleSKURequest
	{

		private AuthenticationInfo authenticationInfoField;

		private BundleProductData productDataField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public BundleProductData ProductData {
			get {
				return this.productDataField;
			}
			set {
				this.productDataField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class BundleProductData : ProductData
	{

		private BomComponentData[] componentsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public BomComponentData[] Components {
			get {
				return this.componentsField;
			}
			set {
				this.componentsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class BomComponentData
	{

		private string supplierSkuField;

		private int quantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string SupplierSku {
			get {
				return this.supplierSkuField;
			}
			set {
				this.supplierSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(BundleProductData))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GiftSetProductData))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(NonWineProductData))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WineProductData))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public abstract partial class ProductData
	{

		private int supplierNumberField;

		private string supplierSkuField;

		private string descriptionField;

		private double retailPriceField;

		private ProductSellingInfo[] sellingInfoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int SupplierNumber {
			get {
				return this.supplierNumberField;
			}
			set {
				this.supplierNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string SupplierSku {
			get {
				return this.supplierSkuField;
			}
			set {
				this.supplierSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public double RetailPrice {
			get {
				return this.retailPriceField;
			}
			set {
				this.retailPriceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 4)]
		public ProductSellingInfo[] SellingInfo {
			get {
				return this.sellingInfoField;
			}
			set {
				this.sellingInfoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class ProductSellingInfo
	{

		private string accountNumberField;

		private string sellingSKUField;

		private string descriptionField;

		private double supplierPaymentField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string SellingSKU {
			get {
				return this.sellingSKUField;
			}
			set {
				this.sellingSKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public double SupplierPayment {
			get {
				return this.supplierPaymentField;
			}
			set {
				this.supplierPaymentField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class GiftSetProductData : ProductData
	{

		private BomComponentData[] componentsField;

		private int caseQuantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public BomComponentData[] Components {
			get {
				return this.componentsField;
			}
			set {
				this.componentsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int CaseQuantity {
			get {
				return this.caseQuantityField;
			}
			set {
				this.caseQuantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class NonWineProductData : ProductData
	{

		private string itemTypeField;

		private int caseQuantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string ItemType {
			get {
				return this.itemTypeField;
			}
			set {
				this.itemTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int CaseQuantity {
			get {
				return this.caseQuantityField;
			}
			set {
				this.caseQuantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class WineProductData : ProductData
	{

		private string colaNumberField;

		private string alcoholTypeField;

		private string countryOfOriginField;

		private string regionOfOriginField;

		private string varietalField;

		private string brandNameField;

		private string fancifulNameField;

		private string vineyardDesignationField;

		private string appellationField;

		private System.Nullable<int> vintageField;

		private int bottleSizeField;

		private double alcoholPercentageField;

		private string attributesField;

		private int caseQuantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string ColaNumber {
			get {
				return this.colaNumberField;
			}
			set {
				this.colaNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AlcoholType {
			get {
				return this.alcoholTypeField;
			}
			set {
				this.alcoholTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string CountryOfOrigin {
			get {
				return this.countryOfOriginField;
			}
			set {
				this.countryOfOriginField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string RegionOfOrigin {
			get {
				return this.regionOfOriginField;
			}
			set {
				this.regionOfOriginField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string Varietal {
			get {
				return this.varietalField;
			}
			set {
				this.varietalField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string BrandName {
			get {
				return this.brandNameField;
			}
			set {
				this.brandNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string FancifulName {
			get {
				return this.fancifulNameField;
			}
			set {
				this.fancifulNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string VineyardDesignation {
			get {
				return this.vineyardDesignationField;
			}
			set {
				this.vineyardDesignationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public string Appellation {
			get {
				return this.appellationField;
			}
			set {
				this.appellationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 9)]
		public System.Nullable<int> Vintage {
			get {
				return this.vintageField;
			}
			set {
				this.vintageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public int BottleSize {
			get {
				return this.bottleSizeField;
			}
			set {
				this.bottleSizeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 11)]
		public double AlcoholPercentage {
			get {
				return this.alcoholPercentageField;
			}
			set {
				this.alcoholPercentageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public string Attributes {
			get {
				return this.attributesField;
			}
			set {
				this.attributesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 13)]
		public int CaseQuantity {
			get {
				return this.caseQuantityField;
			}
			set {
				this.caseQuantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateGiftSetSKURequest
	{

		private AuthenticationInfo authenticationInfoField;

		private GiftSetProductData productDataField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public GiftSetProductData ProductData {
			get {
				return this.productDataField;
			}
			set {
				this.productDataField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateNonWineSKURequest
	{

		private AuthenticationInfo authenticationInfoField;

		private NonWineProductData productDataField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public NonWineProductData ProductData {
			get {
				return this.productDataField;
			}
			set {
				this.productDataField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateWineSKURequest
	{

		private AuthenticationInfo authenticationInfoField;

		private WineProductData productDataField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public WineProductData ProductData {
			get {
				return this.productDataField;
			}
			set {
				this.productDataField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class RefineAddressSearchRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private QASRefineAddress addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public QASRefineAddress Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class QASRefineAddress : QASSearchAddress
	{

		private string refineTokenField;

		private string buildingNumberField;

		private string subBuildingNumberField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string RefineToken {
			get {
				return this.refineTokenField;
			}
			set {
				this.refineTokenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string BuildingNumber {
			get {
				return this.buildingNumberField;
			}
			set {
				this.buildingNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SubBuildingNumber {
			get {
				return this.subBuildingNumberField;
			}
			set {
				this.subBuildingNumberField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(QASRefineAddress))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class QASSearchAddress
	{

		private string companyNameField;

		private string line1Field;

		private string line2Field;

		private string cityField;

		private string stateOrProvinceField;

		private string postalCodeField;

		private string countryCodeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string CompanyName {
			get {
				return this.companyNameField;
			}
			set {
				this.companyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Line1 {
			get {
				return this.line1Field;
			}
			set {
				this.line1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Line2 {
			get {
				return this.line2Field;
			}
			set {
				this.line2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string PostalCode {
			get {
				return this.postalCodeField;
			}
			set {
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string CountryCode {
			get {
				return this.countryCodeField;
			}
			set {
				this.countryCodeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class TrackingEvent
	{

		private System.Nullable<System.DateTime> timestampField;

		private string cityField;

		private string stateOrProvinceField;

		private string descriptionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
		public System.Nullable<System.DateTime> Timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string Description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DtcShipmentLine
	{

		private string sKUField;

		private int quantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DtcShipment
	{

		private string orderIdField;

		private string containerIdField;

		private string shipDateField;

		private string carrierNameField;

		private string trackingNumberField;

		private DtcShipmentStatusEnum statusCodeField;

		private string statusMessageField;

		private DtcShipmentLine[] contentsField;

		private TrackingEvent[] eventsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string ContainerId {
			get {
				return this.containerIdField;
			}
			set {
				this.containerIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string ShipDate {
			get {
				return this.shipDateField;
			}
			set {
				this.shipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string CarrierName {
			get {
				return this.carrierNameField;
			}
			set {
				this.carrierNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string TrackingNumber {
			get {
				return this.trackingNumberField;
			}
			set {
				this.trackingNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public DtcShipmentStatusEnum StatusCode {
			get {
				return this.statusCodeField;
			}
			set {
				this.statusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string StatusMessage {
			get {
				return this.statusMessageField;
			}
			set {
				this.statusMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
		public DtcShipmentLine[] Contents {
			get {
				return this.contentsField;
			}
			set {
				this.contentsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 8)]
		public TrackingEvent[] Events {
			get {
				return this.eventsField;
			}
			set {
				this.eventsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public enum DtcShipmentStatusEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Shipped,

		/// <remarks/>
		InTransit,

		/// <remarks/>
		Delivered,

		/// <remarks/>
		Exception,

		/// <remarks/>
		Returned,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DtcOrderLine))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public abstract partial class OrderLineBase
	{

		private int lineNumberField;

		private int quantityField;

		private string sKUField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int LineNumber {
			get {
				return this.lineNumberField;
			}
			set {
				this.lineNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DtcOrderLine : OrderLineBase
	{

		private double unitPriceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public double UnitPrice {
			get {
				return this.unitPriceField;
			}
			set {
				this.unitPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DtcOrderStatus
	{

		private string orderIdField;

		private string batchIdField;

		private string warehouseCodeField;

		private string orderStatusCodeField;

		private string orderStatusMessageField;

		private string currentHoldField;

		private DtcOrderLine[] linesField;

		private DtcShipment[] shipmentsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string OrderStatusCode {
			get {
				return this.orderStatusCodeField;
			}
			set {
				this.orderStatusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string OrderStatusMessage {
			get {
				return this.orderStatusMessageField;
			}
			set {
				this.orderStatusMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string CurrentHold {
			get {
				return this.currentHoldField;
			}
			set {
				this.currentHoldField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
		public DtcOrderLine[] Lines {
			get {
				return this.linesField;
			}
			set {
				this.linesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
		public DtcShipment[] Shipments {
			get {
				return this.shipmentsField;
			}
			set {
				this.shipmentsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class QASReturnedAddress
	{

		private bool validatedField;

		private QASResultEnum resultField;

		private string refineTokenField;

		private string[] candidatesField;

		private QASSearchAddress addressField;

		private System.Nullable<double> latitudeField;

		private System.Nullable<double> longitudeField;

		private System.Nullable<bool> isResidenceField;

		private bool isPostOfficeBoxField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public bool Validated {
			get {
				return this.validatedField;
			}
			set {
				this.validatedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public QASResultEnum Result {
			get {
				return this.resultField;
			}
			set {
				this.resultField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string RefineToken {
			get {
				return this.refineTokenField;
			}
			set {
				this.refineTokenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
		public string[] Candidates {
			get {
				return this.candidatesField;
			}
			set {
				this.candidatesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public QASSearchAddress Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
		public System.Nullable<double> Latitude {
			get {
				return this.latitudeField;
			}
			set {
				this.latitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
		public System.Nullable<double> Longitude {
			get {
				return this.longitudeField;
			}
			set {
				this.longitudeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
		public System.Nullable<bool> IsResidence {
			get {
				return this.isResidenceField;
			}
			set {
				this.isResidenceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public bool IsPostOfficeBox {
			get {
				return this.isPostOfficeBoxField;
			}
			set {
				this.isPostOfficeBoxField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public enum QASResultEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Verified,

		/// <remarks/>
		InteractionRequired,

		/// <remarks/>
		StreetPartial,

		/// <remarks/>
		PremisesPartial,

		/// <remarks/>
		MultipleMatch,

		/// <remarks/>
		None,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class ErrorReference
	{

		private string nameField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Value {
			get {
				return this.valueField;
			}
			set {
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class ServiceMessage
	{

		private ErrorReference[] referencesField;

		private string codeField;

		private string messageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public ErrorReference[] References {
			get {
				return this.referencesField;
			}
			set {
				this.referencesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Code {
			get {
				return this.codeField;
			}
			set {
				this.codeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Message {
			get {
				return this.messageField;
			}
			set {
				this.messageField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class ServiceOutcome
	{

		private ResultEnum resultField;

		private ServiceMessage[] warningsField;

		private ServiceMessage[] errorsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ResultEnum Result {
			get {
				return this.resultField;
			}
			set {
				this.resultField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public ServiceMessage[] Warnings {
			get {
				return this.warningsField;
			}
			set {
				this.warningsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public ServiceMessage[] Errors {
			get {
				return this.errorsField;
			}
			set {
				this.errorsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public enum ResultEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Success,

		/// <remarks/>
		Failure,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetOrderStatusResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeactivateSKUResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateBundleSKUResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateGiftSetSKUResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateNonWineSKUResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateWineSKUResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(RefineAddressSearchResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchForAddressResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class IServiceResponse
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class GetOrderStatusResponse : IServiceResponse
	{

		private DtcOrderStatus[] orderStatusesField;

		private ServiceOutcome outcomeField;

		private int matchingRecordsField;

		private int recordsRemainingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public DtcOrderStatus[] OrderStatuses {
			get {
				return this.orderStatusesField;
			}
			set {
				this.orderStatusesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int MatchingRecords {
			get {
				return this.matchingRecordsField;
			}
			set {
				this.matchingRecordsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int RecordsRemaining {
			get {
				return this.recordsRemainingField;
			}
			set {
				this.recordsRemainingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class DeactivateSKUResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateBundleSKUResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string wineDirectSkuField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string WineDirectSku {
			get {
				return this.wineDirectSkuField;
			}
			set {
				this.wineDirectSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateGiftSetSKUResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string wineDirectSkuField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string WineDirectSku {
			get {
				return this.wineDirectSkuField;
			}
			set {
				this.wineDirectSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateNonWineSKUResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string wineDirectSkuField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string WineDirectSku {
			get {
				return this.wineDirectSkuField;
			}
			set {
				this.wineDirectSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class CreateWineSKUResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string wineDirectSkuField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string WineDirectSku {
			get {
				return this.wineDirectSkuField;
			}
			set {
				this.wineDirectSkuField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class RefineAddressSearchResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private QASReturnedAddress addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public QASReturnedAddress Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/internal/")]
	public partial class SearchForAddressResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private QASReturnedAddress addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public QASReturnedAddress Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public interface InternalSoapChannel : InternalSoap, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public partial class InternalSoapClient : System.ServiceModel.ClientBase<InternalSoap>, InternalSoap
	{

		/// <summary>
		/// Implement this partial method to configure the service endpoint.
		/// </summary>
		/// <param name="serviceEndpoint">The endpoint to configure</param>
		/// <param name="clientCredentials">The client credentials</param>
		static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

		public InternalSoapClient(EndpointConfiguration endpointConfiguration) :
				base(InternalSoapClient.GetBindingForEndpoint(endpointConfiguration), InternalSoapClient.GetEndpointAddress(endpointConfiguration)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public InternalSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
				base(InternalSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public InternalSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
				base(InternalSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public InternalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
				base(binding, remoteAddress) {
		}

		public System.Threading.Tasks.Task<SearchForAddressResponse> SearchForAddressAsync(SearchForAddressRequest SearchForAddressRequest) {
			return base.Channel.SearchForAddressAsync(SearchForAddressRequest);
		}

		public System.Threading.Tasks.Task<RefineAddressSearchResponse> RefineAddressSearchAsync(RefineAddressSearchRequest RefineAddressSearchRequest) {
			return base.Channel.RefineAddressSearchAsync(RefineAddressSearchRequest);
		}

		public System.Threading.Tasks.Task<CreateWineSKUResponse> CreateWineSKUAsync(CreateWineSKURequest CreateWineSKURequest) {
			return base.Channel.CreateWineSKUAsync(CreateWineSKURequest);
		}

		public System.Threading.Tasks.Task<CreateNonWineSKUResponse> CreateNonWineSKUAsync(CreateNonWineSKURequest CreateNonWineSKURequest) {
			return base.Channel.CreateNonWineSKUAsync(CreateNonWineSKURequest);
		}

		public System.Threading.Tasks.Task<CreateGiftSetSKUResponse> CreateGiftSetSKUAsync(CreateGiftSetSKURequest CreateGiftSetSKURequest) {
			return base.Channel.CreateGiftSetSKUAsync(CreateGiftSetSKURequest);
		}

		public System.Threading.Tasks.Task<CreateBundleSKUResponse> CreateBundleSKUAsync(CreateBundleSKURequest CreateBundleSKURequest) {
			return base.Channel.CreateBundleSKUAsync(CreateBundleSKURequest);
		}

		public System.Threading.Tasks.Task<DeactivateSKUResponse> DeactivateSKUAsync(DeactivateSKURequest DeactivateSKURequest) {
			return base.Channel.DeactivateSKUAsync(DeactivateSKURequest);
		}

		public System.Threading.Tasks.Task<GetOrderStatusResponse> GetOrderStatusAsync(GetOrderStatusRequest GetOrderStatusRequest) {
			return base.Channel.GetOrderStatusAsync(GetOrderStatusRequest);
		}

		public virtual System.Threading.Tasks.Task OpenAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
		}

		public virtual System.Threading.Tasks.Task CloseAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
		}

		private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.InternalSoap)) {
				System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
				result.MaxBufferSize = int.MaxValue;
				result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
				result.MaxReceivedMessageSize = int.MaxValue;
				result.AllowCookies = true;
				return result;
			}
			if ((endpointConfiguration == EndpointConfiguration.InternalSoap12)) {
				System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
				System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
				textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
				result.Elements.Add(textBindingElement);
				System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
				httpBindingElement.AllowCookies = true;
				httpBindingElement.MaxBufferSize = int.MaxValue;
				httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
				result.Elements.Add(httpBindingElement);
				return result;
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.InternalSoap)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/0/internal.asmx");
			}
			if ((endpointConfiguration == EndpointConfiguration.InternalSoap12)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/0/internal.asmx");
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		public enum EndpointConfiguration
		{

			InternalSoap,

			InternalSoap12,
		}
	}
}
