//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineDirect.v40
{

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://winedirect.com/4/0/dtc/", ConfigurationName = "dtcSoap")]
	public interface dtcSoap
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/CheckSystemStatus", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CheckSystemStatusResponse> CheckSystemStatusAsync(CheckSystemStatusRequest CheckSystemStatusRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/SubmitOrders", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<SubmitOrdersResponse> SubmitOrdersAsync(SubmitOrdersRequest SubmitOrdersRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/CancelOrder", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<CancelOrderResponse> CancelOrderAsync(CancelOrderRequest CancelOrderRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/GetOrderStatus", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetOrderStatusResponse> GetOrderStatusAsync(GetOrderStatusRequest GetOrderStatusRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/GetShipments", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetShipmentsResponse> GetShipmentsAsync(GetShipmentsRequest GetShipmentsRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/GetShipmentUpdates", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetShipmentUpdatesResponse> GetShipmentUpdatesAsync(GetShipmentUpdatesRequest GetShipmentUpdatesRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/GetInventory", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetInventoryResponse> GetInventoryAsync(GetInventoryRequest GetInventoryRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/ValidateAddress", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<ValidateAddressResponse> ValidateAddressAsync(ValidateAddressRequest ValidateAddressRequest);

		[System.ServiceModel.OperationContractAttribute(Action = "http://winedirect.com/4/0/dtc/GetProducts", ReplyAction = "*")]
		[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderLineBase))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(IServiceResponse))]
		System.Threading.Tasks.Task<GetProductsResponse> GetProductsAsync(GetProductsRequest GetProductsRequest);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class CheckSystemStatusRequest
	{

		private AuthenticationInfo authenticationInfoField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class AuthenticationInfo
	{

		private string userNameField;

		private string passwordField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string UserName {
			get {
				return this.userNameField;
			}
			set {
				this.userNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Password {
			get {
				return this.passwordField;
			}
			set {
				this.passwordField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetProductsRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private string sKUField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ValidateAddressRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private AddressInfo addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public AddressInfo Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class AddressInfo
	{

		private string companyNameField;

		private string line1Field;

		private string line2Field;

		private string line3Field;

		private string cityField;

		private string stateOrProvinceField;

		private string postalCodeField;

		private string countryCodeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string CompanyName {
			get {
				return this.companyNameField;
			}
			set {
				this.companyNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Line1 {
			get {
				return this.line1Field;
			}
			set {
				this.line1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Line2 {
			get {
				return this.line2Field;
			}
			set {
				this.line2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string Line3 {
			get {
				return this.line3Field;
			}
			set {
				this.line3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string PostalCode {
			get {
				return this.postalCodeField;
			}
			set {
				this.postalCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string CountryCode {
			get {
				return this.countryCodeField;
			}
			set {
				this.countryCodeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetInventoryRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private string warehouseCodeField;

		private string subinventoryCodeField;

		private string sKUField;

		private string startingSKUField;

		private bool availableOnlyField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string SubinventoryCode {
			get {
				return this.subinventoryCodeField;
			}
			set {
				this.subinventoryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string StartingSKU {
			get {
				return this.startingSKUField;
			}
			set {
				this.startingSKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public bool AvailableOnly {
			get {
				return this.availableOnlyField;
			}
			set {
				this.availableOnlyField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetShipmentUpdatesRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private string searchStartTimeField;

		private string searchEndTimeField;

		private string startingContainerIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SearchStartTime {
			get {
				return this.searchStartTimeField;
			}
			set {
				this.searchStartTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string SearchEndTime {
			get {
				return this.searchEndTimeField;
			}
			set {
				this.searchEndTimeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string StartingContainerId {
			get {
				return this.startingContainerIdField;
			}
			set {
				this.startingContainerIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetShipmentsRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private string searchFromShipDateField;

		private string searchToShipDateField;

		private string stateOrProvinceField;

		private DtcShipmentStatusEnum statusCodeField;

		private string startingContainerIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SearchFromShipDate {
			get {
				return this.searchFromShipDateField;
			}
			set {
				this.searchFromShipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string SearchToShipDate {
			get {
				return this.searchToShipDateField;
			}
			set {
				this.searchToShipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public DtcShipmentStatusEnum StatusCode {
			get {
				return this.statusCodeField;
			}
			set {
				this.statusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string StartingContainerId {
			get {
				return this.startingContainerIdField;
			}
			set {
				this.startingContainerIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public enum DtcShipmentStatusEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Shipped,

		/// <remarks/>
		InTransit,

		/// <remarks/>
		Delivered,

		/// <remarks/>
		Exception,

		/// <remarks/>
		Returned,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetOrderStatusRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private bool searchByBatchIdSpecified1Field;

		private string batchIdField;

		private bool searchByOrderIdsSpecified1Field;

		private string[] orderIdsField;

		private bool searchByStatusSpecified1Field;

		private string statusField;

		private bool searchByReferenceSpecified1Field;

		private string reference1Field;

		private string reference2Field;

		private string reference3Field;

		private string startingOrderIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByBatchIdSpecified", Order = 2)]
		public bool SearchByBatchIdSpecified1 {
			get {
				return this.searchByBatchIdSpecified1Field;
			}
			set {
				this.searchByBatchIdSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByOrderIdsSpecified", Order = 4)]
		public bool SearchByOrderIdsSpecified1 {
			get {
				return this.searchByOrderIdsSpecified1Field;
			}
			set {
				this.searchByOrderIdsSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
		public string[] OrderIds {
			get {
				return this.orderIdsField;
			}
			set {
				this.orderIdsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByStatusSpecified", Order = 6)]
		public bool SearchByStatusSpecified1 {
			get {
				return this.searchByStatusSpecified1Field;
			}
			set {
				this.searchByStatusSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string Status {
			get {
				return this.statusField;
			}
			set {
				this.statusField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SearchByReferenceSpecified", Order = 8)]
		public bool SearchByReferenceSpecified1 {
			get {
				return this.searchByReferenceSpecified1Field;
			}
			set {
				this.searchByReferenceSpecified1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public string Reference1 {
			get {
				return this.reference1Field;
			}
			set {
				this.reference1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public string Reference2 {
			get {
				return this.reference2Field;
			}
			set {
				this.reference2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 11)]
		public string Reference3 {
			get {
				return this.reference3Field;
			}
			set {
				this.reference3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public string StartingOrderId {
			get {
				return this.startingOrderIdField;
			}
			set {
				this.startingOrderIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class CancelOrderRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private string orderIdField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ConsumerInfo
	{

		private string consumerIdField;

		private string firstNameField;

		private string middleNameField;

		private string lastNameField;

		private string emailAddressField;

		private string telephoneNumberField;

		private AddressInfo addressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string ConsumerId {
			get {
				return this.consumerIdField;
			}
			set {
				this.consumerIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string FirstName {
			get {
				return this.firstNameField;
			}
			set {
				this.firstNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string MiddleName {
			get {
				return this.middleNameField;
			}
			set {
				this.middleNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string LastName {
			get {
				return this.lastNameField;
			}
			set {
				this.lastNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string EmailAddress {
			get {
				return this.emailAddressField;
			}
			set {
				this.emailAddressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string TelephoneNumber {
			get {
				return this.telephoneNumberField;
			}
			set {
				this.telephoneNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public AddressInfo Address {
			get {
				return this.addressField;
			}
			set {
				this.addressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class DtcOrder
	{

		private string orderIdField;

		private string batchIdField;

		private DtcOrderTypeEnum orderTypeField;

		private bool onSitePurchaseField;

		private string warehouseCodeField;

		private string subinventoryCodeField;

		private string notificationCodeField;

		private string packingSlipCodeField;

		private string giftMessageField;

		private string reference1Field;

		private string reference2Field;

		private string reference3Field;

		private ConsumerInfo soldToField;

		private ConsumerInfo shipToField;

		private string requestedPriorityField;

		private string requestedShipDateField;

		private string shippingInstructionsField;

		private double shippingChargesField;

		private double handlingChargesField;

		private double salesTaxField;

		private double insuranceField;

		private double totalSaleField;

		private DtcOrderLine[] orderLinesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public DtcOrderTypeEnum OrderType {
			get {
				return this.orderTypeField;
			}
			set {
				this.orderTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public bool OnSitePurchase {
			get {
				return this.onSitePurchaseField;
			}
			set {
				this.onSitePurchaseField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string SubinventoryCode {
			get {
				return this.subinventoryCodeField;
			}
			set {
				this.subinventoryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string NotificationCode {
			get {
				return this.notificationCodeField;
			}
			set {
				this.notificationCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 7)]
		public string PackingSlipCode {
			get {
				return this.packingSlipCodeField;
			}
			set {
				this.packingSlipCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 8)]
		public string GiftMessage {
			get {
				return this.giftMessageField;
			}
			set {
				this.giftMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public string Reference1 {
			get {
				return this.reference1Field;
			}
			set {
				this.reference1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 10)]
		public string Reference2 {
			get {
				return this.reference2Field;
			}
			set {
				this.reference2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 11)]
		public string Reference3 {
			get {
				return this.reference3Field;
			}
			set {
				this.reference3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 12)]
		public ConsumerInfo SoldTo {
			get {
				return this.soldToField;
			}
			set {
				this.soldToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 13)]
		public ConsumerInfo ShipTo {
			get {
				return this.shipToField;
			}
			set {
				this.shipToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 14)]
		public string RequestedPriority {
			get {
				return this.requestedPriorityField;
			}
			set {
				this.requestedPriorityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 15)]
		public string RequestedShipDate {
			get {
				return this.requestedShipDateField;
			}
			set {
				this.requestedShipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 16)]
		public string ShippingInstructions {
			get {
				return this.shippingInstructionsField;
			}
			set {
				this.shippingInstructionsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 17)]
		public double ShippingCharges {
			get {
				return this.shippingChargesField;
			}
			set {
				this.shippingChargesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 18)]
		public double HandlingCharges {
			get {
				return this.handlingChargesField;
			}
			set {
				this.handlingChargesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 19)]
		public double SalesTax {
			get {
				return this.salesTaxField;
			}
			set {
				this.salesTaxField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 20)]
		public double Insurance {
			get {
				return this.insuranceField;
			}
			set {
				this.insuranceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 21)]
		public double TotalSale {
			get {
				return this.totalSaleField;
			}
			set {
				this.totalSaleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 22)]
		public DtcOrderLine[] OrderLines {
			get {
				return this.orderLinesField;
			}
			set {
				this.orderLinesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public enum DtcOrderTypeEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Club,

		/// <remarks/>
		Daily,

		/// <remarks/>
		Special,

		/// <remarks/>
		Sample,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class DtcOrderLine : OrderLineBase
	{

		private double unitPriceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public double UnitPrice {
			get {
				return this.unitPriceField;
			}
			set {
				this.unitPriceField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(DtcOrderLine))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public abstract partial class OrderLineBase
	{

		private int lineNumberField;

		private int quantityField;

		private string sKUField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public int LineNumber {
			get {
				return this.lineNumberField;
			}
			set {
				this.lineNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class SubmitOrdersRequest
	{

		private AuthenticationInfo authenticationInfoField;

		private string accountNumberField;

		private DtcOrder[] ordersField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public AuthenticationInfo AuthenticationInfo {
			get {
				return this.authenticationInfoField;
			}
			set {
				this.authenticationInfoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string AccountNumber {
			get {
				return this.accountNumberField;
			}
			set {
				this.accountNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public DtcOrder[] Orders {
			get {
				return this.ordersField;
			}
			set {
				this.ordersField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class Product
	{

		private string sKUField;

		private string wineDirectSKUField;

		private string descriptionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string WineDirectSKU {
			get {
				return this.wineDirectSKUField;
			}
			set {
				this.wineDirectSKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class InventoryItem
	{

		private string warehouseCodeField;

		private string subinventoryCodeField;

		private string sKUField;

		private int quantityOnHandField;

		private int quantityOnOrdersField;

		private int quantityAvailableField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string SubinventoryCode {
			get {
				return this.subinventoryCodeField;
			}
			set {
				this.subinventoryCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int QuantityOnHand {
			get {
				return this.quantityOnHandField;
			}
			set {
				this.quantityOnHandField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public int QuantityOnOrders {
			get {
				return this.quantityOnOrdersField;
			}
			set {
				this.quantityOnOrdersField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public int QuantityAvailable {
			get {
				return this.quantityAvailableField;
			}
			set {
				this.quantityAvailableField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class TrackingEvent
	{

		private System.Nullable<System.DateTime> timestampField;

		private string cityField;

		private string stateOrProvinceField;

		private string descriptionField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
		public System.Nullable<System.DateTime> Timestamp {
			get {
				return this.timestampField;
			}
			set {
				this.timestampField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string City {
			get {
				return this.cityField;
			}
			set {
				this.cityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string StateOrProvince {
			get {
				return this.stateOrProvinceField;
			}
			set {
				this.stateOrProvinceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string Description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class DtcShipmentLine
	{

		private string sKUField;

		private int quantityField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string SKU {
			get {
				return this.sKUField;
			}
			set {
				this.sKUField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public int Quantity {
			get {
				return this.quantityField;
			}
			set {
				this.quantityField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class DtcShipment
	{

		private string orderIdField;

		private string containerIdField;

		private string shipDateField;

		private string carrierNameField;

		private string trackingNumberField;

		private DtcShipmentStatusEnum statusCodeField;

		private string statusMessageField;

		private DtcShipmentLine[] contentsField;

		private TrackingEvent[] eventsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string ContainerId {
			get {
				return this.containerIdField;
			}
			set {
				this.containerIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string ShipDate {
			get {
				return this.shipDateField;
			}
			set {
				this.shipDateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string CarrierName {
			get {
				return this.carrierNameField;
			}
			set {
				this.carrierNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string TrackingNumber {
			get {
				return this.trackingNumberField;
			}
			set {
				this.trackingNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public DtcShipmentStatusEnum StatusCode {
			get {
				return this.statusCodeField;
			}
			set {
				this.statusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 6)]
		public string StatusMessage {
			get {
				return this.statusMessageField;
			}
			set {
				this.statusMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
		public DtcShipmentLine[] Contents {
			get {
				return this.contentsField;
			}
			set {
				this.contentsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 8)]
		public TrackingEvent[] Events {
			get {
				return this.eventsField;
			}
			set {
				this.eventsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class DtcOrderStatus
	{

		private string orderIdField;

		private string batchIdField;

		private string warehouseCodeField;

		private string orderStatusCodeField;

		private string orderStatusMessageField;

		private string currentHoldField;

		private DtcOrderLine[] linesField;

		private DtcShipment[] shipmentsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string OrderId {
			get {
				return this.orderIdField;
			}
			set {
				this.orderIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string BatchId {
			get {
				return this.batchIdField;
			}
			set {
				this.batchIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string WarehouseCode {
			get {
				return this.warehouseCodeField;
			}
			set {
				this.warehouseCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public string OrderStatusCode {
			get {
				return this.orderStatusCodeField;
			}
			set {
				this.orderStatusCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public string OrderStatusMessage {
			get {
				return this.orderStatusMessageField;
			}
			set {
				this.orderStatusMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public string CurrentHold {
			get {
				return this.currentHoldField;
			}
			set {
				this.currentHoldField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
		public DtcOrderLine[] Lines {
			get {
				return this.linesField;
			}
			set {
				this.linesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
		public DtcShipment[] Shipments {
			get {
				return this.shipmentsField;
			}
			set {
				this.shipmentsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ErrorReference
	{

		private string nameField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string Name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Value {
			get {
				return this.valueField;
			}
			set {
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ServiceMessage
	{

		private ErrorReference[] referencesField;

		private string codeField;

		private string messageField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public ErrorReference[] References {
			get {
				return this.referencesField;
			}
			set {
				this.referencesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public string Code {
			get {
				return this.codeField;
			}
			set {
				this.codeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string Message {
			get {
				return this.messageField;
			}
			set {
				this.messageField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ServiceOutcome
	{

		private ResultEnum resultField;

		private ServiceMessage[] warningsField;

		private ServiceMessage[] errorsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ResultEnum Result {
			get {
				return this.resultField;
			}
			set {
				this.resultField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public ServiceMessage[] Warnings {
			get {
				return this.warningsField;
			}
			set {
				this.warningsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		public ServiceMessage[] Errors {
			get {
				return this.errorsField;
			}
			set {
				this.errorsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public enum ResultEnum
	{

		/// <remarks/>
		NotSet,

		/// <remarks/>
		Success,

		/// <remarks/>
		Failure,
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetProductsResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateAddressResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetInventoryResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetShipmentUpdatesResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetShipmentsResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetOrderStatusResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelOrderResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubmitOrdersResponse))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckSystemStatusResponse))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class IServiceResponse
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetProductsResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private Product[] itemsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public Product[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class ValidateAddressResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private bool addressValidatedField;

		private string validatedByField;

		private int validationScoreField;

		private AddressInfo correctedAddressField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public bool AddressValidated {
			get {
				return this.addressValidatedField;
			}
			set {
				this.addressValidatedField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public string ValidatedBy {
			get {
				return this.validatedByField;
			}
			set {
				this.validatedByField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int ValidationScore {
			get {
				return this.validationScoreField;
			}
			set {
				this.validationScoreField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public AddressInfo CorrectedAddress {
			get {
				return this.correctedAddressField;
			}
			set {
				this.correctedAddressField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetInventoryResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private InventoryItem[] itemsField;

		private int matchingRecordsField;

		private int recordsRemainingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public InventoryItem[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int MatchingRecords {
			get {
				return this.matchingRecordsField;
			}
			set {
				this.matchingRecordsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int RecordsRemaining {
			get {
				return this.recordsRemainingField;
			}
			set {
				this.recordsRemainingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetShipmentUpdatesResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private DtcShipment[] shipmentsField;

		private int matchingRecordsField;

		private int recordsRemainingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public DtcShipment[] Shipments {
			get {
				return this.shipmentsField;
			}
			set {
				this.shipmentsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int MatchingRecords {
			get {
				return this.matchingRecordsField;
			}
			set {
				this.matchingRecordsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int RecordsRemaining {
			get {
				return this.recordsRemainingField;
			}
			set {
				this.recordsRemainingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetShipmentsResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private DtcShipment[] shipmentsField;

		private int matchingRecordsField;

		private int recordsRemainingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public DtcShipment[] Shipments {
			get {
				return this.shipmentsField;
			}
			set {
				this.shipmentsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int MatchingRecords {
			get {
				return this.matchingRecordsField;
			}
			set {
				this.matchingRecordsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int RecordsRemaining {
			get {
				return this.recordsRemainingField;
			}
			set {
				this.recordsRemainingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class GetOrderStatusResponse : IServiceResponse
	{

		private DtcOrderStatus[] orderStatusesField;

		private ServiceOutcome outcomeField;

		private int matchingRecordsField;

		private int recordsRemainingField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		public DtcOrderStatus[] OrderStatuses {
			get {
				return this.orderStatusesField;
			}
			set {
				this.orderStatusesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public int MatchingRecords {
			get {
				return this.matchingRecordsField;
			}
			set {
				this.matchingRecordsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public int RecordsRemaining {
			get {
				return this.recordsRemainingField;
			}
			set {
				this.recordsRemainingField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class CancelOrderResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		private string[] messagesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		public string[] Messages {
			get {
				return this.messagesField;
			}
			set {
				this.messagesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class SubmitOrdersResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://winedirect.com/4/0/dtc/")]
	public partial class CheckSystemStatusResponse : IServiceResponse
	{

		private ServiceOutcome outcomeField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public ServiceOutcome Outcome {
			get {
				return this.outcomeField;
			}
			set {
				this.outcomeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public interface dtcSoapChannel : dtcSoap, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
	public partial class dtcSoapClient : System.ServiceModel.ClientBase<dtcSoap>, dtcSoap
	{

		/// <summary>
		/// Implement this partial method to configure the service endpoint.
		/// </summary>
		/// <param name="serviceEndpoint">The endpoint to configure</param>
		/// <param name="clientCredentials">The client credentials</param>
		static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

		public dtcSoapClient(EndpointConfiguration endpointConfiguration) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), dtcSoapClient.GetEndpointAddress(endpointConfiguration)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
				base(dtcSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public dtcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
				base(binding, remoteAddress) {
		}

		public System.Threading.Tasks.Task<CheckSystemStatusResponse> CheckSystemStatusAsync(CheckSystemStatusRequest CheckSystemStatusRequest) {
			return base.Channel.CheckSystemStatusAsync(CheckSystemStatusRequest);
		}

		public System.Threading.Tasks.Task<SubmitOrdersResponse> SubmitOrdersAsync(SubmitOrdersRequest SubmitOrdersRequest) {
			return base.Channel.SubmitOrdersAsync(SubmitOrdersRequest);
		}

		public System.Threading.Tasks.Task<CancelOrderResponse> CancelOrderAsync(CancelOrderRequest CancelOrderRequest) {
			return base.Channel.CancelOrderAsync(CancelOrderRequest);
		}

		public System.Threading.Tasks.Task<GetOrderStatusResponse> GetOrderStatusAsync(GetOrderStatusRequest GetOrderStatusRequest) {
			return base.Channel.GetOrderStatusAsync(GetOrderStatusRequest);
		}

		public System.Threading.Tasks.Task<GetShipmentsResponse> GetShipmentsAsync(GetShipmentsRequest GetShipmentsRequest) {
			return base.Channel.GetShipmentsAsync(GetShipmentsRequest);
		}

		public System.Threading.Tasks.Task<GetShipmentUpdatesResponse> GetShipmentUpdatesAsync(GetShipmentUpdatesRequest GetShipmentUpdatesRequest) {
			return base.Channel.GetShipmentUpdatesAsync(GetShipmentUpdatesRequest);
		}

		public System.Threading.Tasks.Task<GetInventoryResponse> GetInventoryAsync(GetInventoryRequest GetInventoryRequest) {
			return base.Channel.GetInventoryAsync(GetInventoryRequest);
		}

		public System.Threading.Tasks.Task<ValidateAddressResponse> ValidateAddressAsync(ValidateAddressRequest ValidateAddressRequest) {
			return base.Channel.ValidateAddressAsync(ValidateAddressRequest);
		}

		public System.Threading.Tasks.Task<GetProductsResponse> GetProductsAsync(GetProductsRequest GetProductsRequest) {
			return base.Channel.GetProductsAsync(GetProductsRequest);
		}

		public virtual System.Threading.Tasks.Task OpenAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
		}

		public virtual System.Threading.Tasks.Task CloseAsync() {
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
		}

		private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap)) {
				System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
				result.MaxBufferSize = int.MaxValue;
				result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
				result.MaxReceivedMessageSize = int.MaxValue;
				result.AllowCookies = true;
				return result;
			}
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap12)) {
				System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
				System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
				textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
				result.Elements.Add(textBindingElement);
				System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
				httpBindingElement.AllowCookies = true;
				httpBindingElement.MaxBufferSize = int.MaxValue;
				httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
				result.Elements.Add(httpBindingElement);
				return result;
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/0/dtc.asmx");
			}
			if ((endpointConfiguration == EndpointConfiguration.dtcSoap12)) {
				return new System.ServiceModel.EndpointAddress("http://webservices-test.winedirect.com/4/0/dtc.asmx");
			}
			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		public enum EndpointConfiguration
		{

			dtcSoap,

			dtcSoap12,
		}
	}
}
